/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotoTEC.vista;

import lotoTEC.estructuras.DoubleLinkedList;
import lotoTEC.estructuras.DoubleLinkedNode;
import lotoTEC.logica.GestionPedido;
import lotoTEC.logica.GestionSorteo;
import lotoTEC.logica.ModeladorTablas;
import lotoTEC.logica.Sorteo;
import lotoTEC.logica.TipoSorteo;
import lotoTEC.logica.Tiquete;

/**
 *
 * @author Mata
 */
public class Sorteos extends javax.swing.JFrame {

    /**
     * Creates new form Sorteos
     */
    private GestionSorteo gestionSorteo;
    
    public GestionSorteo getGestionSorteo() {
        return gestionSorteo;
    }

    public void setGestionSorteo(GestionSorteo gestionSorteo) {
        this.gestionSorteo = gestionSorteo;
    }    
    public Sorteos() {
        initComponents();
        this.gestionSorteo = new GestionSorteo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        txtTipo = new javax.swing.JComboBox<>();
        labelEmisiones = new javax.swing.JLabel();
        txtEmisiones = new javax.swing.JTextField();
        labelFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        botonIngresarSorteo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSorteos = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        txtEliminar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonEditar = new javax.swing.JButton();
        botonTipo = new javax.swing.JButton();
        txttipo2 = new javax.swing.JComboBox<>();
        txtBuscarFecha = new javax.swing.JTextField();
        botonBusquedaFecha = new javax.swing.JButton();
        txtBusquedaNombre = new javax.swing.JTextField();
        botonBusquedaNombre = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        labelTitulo1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmisor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipoSorteo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoSorteo = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTiquetes = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtTiquetesSorteo = new javax.swing.JTextField();
        botonTiqueteSorteos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtPrecioInicial = new javax.swing.JTextField();
        botonBusquedaNumero = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCodigoBusquedaNumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioFinal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        botonEliminarTiquete = new javax.swing.JButton();
        pedidos = new javax.swing.JButton();

        jLabel12.setText("Codigo Sorteo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo.setText("Registrar Sorteo");

        labelNombre.setText("Nombre: ");

        jLabel1.setText("Codigo: ");

        labelTipo.setText("Tipo Sorteo:");

        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loteria", "Lotto", "Bingo", "Tiempos" }));

        labelEmisiones.setText("Emisiones: ");

        labelFecha.setText("Fecha: ");

        botonIngresarSorteo.setText("Ingresar");
        botonIngresarSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarSorteoActionPerformed(evt);
            }
        });

        tablaSorteos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Emisiones", "Fecha", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tablaSorteos);

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo de Sorteo");

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonTipo.setText("Buscar por tipo");
        botonTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTipoActionPerformed(evt);
            }
        });

        txttipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loteria", "Lotto", "Bingo", "Tiempos" }));

        botonBusquedaFecha.setText("Buscar por fecha");
        botonBusquedaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaFechaActionPerformed(evt);
            }
        });

        botonBusquedaNombre.setText("Buscar por nombre");
        botonBusquedaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaNombreActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        labelTitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo1.setText("Gestion de Tiquetes");

        jLabel3.setText("Emisor:");

        jLabel4.setText("Tipo Sorteo:");

        jLabel5.setText("Precio:");

        jLabel6.setText("Numero:");

        jLabel7.setText("Codigo Sorteo:");

        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        tablaTiquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Emisor", "Tipo Sorteo", "Precio", "Numero", "Codigo Sorteo", "Usuario"
            }
        ));
        jScrollPane2.setViewportView(tablaTiquetes);

        jLabel8.setText("Busqueda por Sorteo");

        botonTiqueteSorteos.setText("Buscar");
        botonTiqueteSorteos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiqueteSorteosActionPerformed(evt);
            }
        });

        jLabel9.setText("Precio Inicial");

        botonBusquedaNumero.setText("Buscar por precio");
        botonBusquedaNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaNumeroActionPerformed(evt);
            }
        });

        jLabel10.setText("Codigo Sorteo");

        jLabel11.setText("Precio Final");

        jLabel13.setText("Eliminar Tiquete");

        botonEliminarTiquete.setText("Eliminar ");
        botonEliminarTiquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTiqueteActionPerformed(evt);
            }
        });

        pedidos.setText("Pedidos");
        pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(botonIngresarSorteo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonActualizar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTipoSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(labelNombre))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                                .addComponent(txtNombre)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelTipo)
                                                .addComponent(labelEmisiones)
                                                .addComponent(labelFecha))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtEmisiones)
                                                .addComponent(txtTipo, 0, 153, Short.MAX_VALUE)
                                                .addComponent(txtFecha)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botonIngresar)
                                        .addComponent(txtCodigoSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pedidos))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(labelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBusquedaNombre)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEliminar)
                    .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttipo2, 0, 153, Short.MAX_VALUE)
                    .addComponent(botonBusquedaFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscarFecha)
                    .addComponent(botonBusquedaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(txtTiquetesSorteo)
                    .addComponent(botonTiqueteSorteos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrecioInicial)
                    .addComponent(botonBusquedaNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodigoBusquedaNumero)
                    .addComponent(jLabel11)
                    .addComponent(txtPrecioFinal)
                    .addComponent(jLabel13)
                    .addComponent(botonEliminarTiquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTitulo)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTipo)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmisiones)
                            .addComponent(txtEmisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFecha)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonIngresarSorteo)
                            .addComponent(botonActualizar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(botonEditar)
                        .addGap(47, 47, 47)
                        .addComponent(txttipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonTipo)
                        .addGap(43, 43, 43)
                        .addComponent(txtBuscarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonBusquedaFecha)
                        .addGap(32, 32, 32)
                        .addComponent(txtBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonBusquedaNombre))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTipoSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCodigoSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botonIngresar)
                        .addGap(37, 37, 37)
                        .addComponent(pedidos))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTiquetesSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonTiqueteSorteos)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoBusquedaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBusquedaNumero)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEliminarTiquete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarSorteoActionPerformed
        String nombreSorteo, fecha;
        int codigo, emisiones;
        nombreSorteo = this.txtNombre.getText();
        fecha = this.txtFecha.getText();
        codigo= Integer.parseInt(this.txtCodigo.getText());
        emisiones = Integer.parseInt(this.txtEmisiones.getText());
        
        if (this.txtTipo.getSelectedItem().equals("Loteria")) {           
            this.gestionSorteo.agregarSorteo(new Sorteo(nombreSorteo, codigo, TipoSorteo.LOTERIA, emisiones, fecha));                       
            actualizarTabla();
        }
         if (this.txtTipo.getSelectedItem().equals("Lotto")) {             
            Sorteo sorteo1 = new Sorteo(nombreSorteo, codigo, TipoSorteo.LOTTO, emisiones, fecha);
            this.gestionSorteo.agregarSorteo(sorteo1);
            actualizarTabla();
        }       
         if (this.txtTipo.getSelectedItem().equals("Bingo")) {
            Sorteo sorteo1 = new Sorteo(nombreSorteo, codigo, TipoSorteo.BINGO, emisiones, fecha);
            this.gestionSorteo.agregarSorteo(sorteo1);
            actualizarTabla();
        } 
         if (this.txtTipo.getSelectedItem().equals("Tiempos")) {
            Sorteo sorteo1 = new Sorteo(nombreSorteo, codigo, TipoSorteo.TIEMPO, emisiones, fecha);
            this.gestionSorteo.agregarSorteo(sorteo1);
            actualizarTabla();
        }  
        
    }//GEN-LAST:event_botonIngresarSorteoActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int codigo= Integer.parseInt(this.txtEliminar.getText());
        Sorteo sorteo = this.gestionSorteo.consultarPorCodigo(codigo);
        System.out.println(sorteo.getNombreSorteo());
        this.gestionSorteo.getListaSorteo().delete(sorteo);
        actualizarTabla();
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
            String nombreSorteo, fecha;
        int codigo, emisiones;
        nombreSorteo = this.txtNombre.getText();
        fecha = this.txtFecha.getText();
        codigo= Integer.parseInt(this.txtCodigo.getText());
        emisiones = Integer.parseInt(this.txtEmisiones.getText());
        Sorteo editado = this.gestionSorteo.consultarPorCodigo(Integer.parseInt(this.txtEliminar.getText()));
        
        if (this.txtTipo.getSelectedItem().equals("Loteria")) {           
            Sorteo sorteo = new Sorteo(nombreSorteo, codigo, TipoSorteo.LOTERIA, emisiones, fecha);                       
            this.gestionSorteo.getListaSorteo().update(sorteo, editado);
            System.out.println("va a actuualizar");
            actualizarTabla();
        }
         if (this.txtTipo.getSelectedItem().equals("Lotto")) {             
            Sorteo sorteo = new Sorteo(nombreSorteo, codigo, TipoSorteo.LOTTO, emisiones, fecha);
            this.gestionSorteo.getListaSorteo().update(sorteo, editado);
            actualizarTabla();
        }       
         if (this.txtTipo.getSelectedItem().equals("Bingo")) {
            Sorteo sorteo = new Sorteo(nombreSorteo, codigo, TipoSorteo.BINGO, emisiones, fecha);
            this.gestionSorteo.getListaSorteo().update(sorteo, editado);
            actualizarTabla();

        } 
         if (this.txtTipo.getSelectedItem().equals("Tiempos")) {
            Sorteo sorteo = new Sorteo(nombreSorteo, codigo, TipoSorteo.TIEMPO, emisiones, fecha);
            this.gestionSorteo.getListaSorteo().update(sorteo, editado);
            actualizarTabla();
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTipoActionPerformed
        if (this.txttipo2.getSelectedItem().equals("Loteria")) {           
            actualizarTablaTipo(this.gestionSorteo.consultarTipo(TipoSorteo.LOTERIA));
        }
         if (this.txttipo2.getSelectedItem().equals("Lotto")) {             
            actualizarTablaTipo(this.gestionSorteo.consultarTipo(TipoSorteo.LOTTO));
        }       
         if (this.txttipo2.getSelectedItem().equals("Bingo")) {
            actualizarTablaTipo(this.gestionSorteo.consultarTipo(TipoSorteo.BINGO));

        } 
         if (this.txttipo2.getSelectedItem().equals("Tiempos")) {
            actualizarTablaTipo(this.gestionSorteo.consultarTipo(TipoSorteo.TIEMPO));
        }
    }//GEN-LAST:event_botonTipoActionPerformed

    private void botonBusquedaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaFechaActionPerformed
        actualizarTablaTipo(this.gestionSorteo.consultarFecha(this.txtBuscarFecha.getText()));
    }//GEN-LAST:event_botonBusquedaFechaActionPerformed

    private void botonBusquedaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaNombreActionPerformed
       actualizarTablaTipo(this.gestionSorteo.consultarPorNombre(this.txtBusquedaNombre.getText()));
    }//GEN-LAST:event_botonBusquedaNombreActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        String emisor = this.txtEmisor.getText();
        String tipoSorteo = this.txtTipoSorteo.getText();
        int precio = Integer.parseInt(this.txtPrecio.getText());
        int numero = Integer.parseInt(this.txtNumero.getText());
        int codigo = Integer.parseInt(this.txtCodigoSorteo.getText());
        Tiquete tiquete = new Tiquete(emisor, tipoSorteo, precio, numero, this.gestionSorteo.consultarPorCodigo(codigo));
        this.gestionSorteo.añadirTiquete(tiquete, codigo);
        actualizarTablaTiquetes(this.gestionSorteo.consultarPorCodigo(codigo).getGestorTiquetes().getListaTiquete());
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonTiqueteSorteosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiqueteSorteosActionPerformed
       Sorteo sorteo = this.gestionSorteo.consultarPorCodigo(Integer.parseInt(this.txtTiquetesSorteo.getText()));
        actualizarTablaTiquetes(sorteo.getGestorTiquetes().getListaTiquete());
    }//GEN-LAST:event_botonTiqueteSorteosActionPerformed

    private void botonBusquedaNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaNumeroActionPerformed
       Sorteo sorteo = this.gestionSorteo.consultarPorCodigo(Integer.parseInt(this.txtCodigoBusquedaNumero.getText()));
       int inicial = Integer.parseInt(this.txtPrecioInicial.getText());
       int xfinal = Integer.parseInt(this.txtPrecioFinal.getText());
        actualizarTablaTiquetes(sorteo.getGestorTiquetes().consultarRangoPrecio(inicial, xfinal));
       

    }//GEN-LAST:event_botonBusquedaNumeroActionPerformed

    private void botonEliminarTiqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTiqueteActionPerformed

       int row = tablaTiquetes.getSelectedRow();
       String emisor = tablaTiquetes.getModel().getValueAt(row, 0).toString();
       String tipoSorteo = tablaTiquetes.getModel().getValueAt(row, 1).toString();
       int precio = Integer.parseInt(tablaTiquetes.getModel().getValueAt(row, 2).toString());
       int numero = Integer.parseInt(tablaTiquetes.getModel().getValueAt(row, 3).toString());
       int codigoSorteo = Integer.parseInt(tablaTiquetes.getModel().getValueAt(row, 4).toString());
       Sorteo sorteo = this.gestionSorteo.consultarPorCodigo(codigoSorteo);
       Tiquete tiquete = new Tiquete(emisor, tipoSorteo, precio, numero, sorteo);
       sorteo.getGestorTiquetes().eliminarTiquete(tiquete);
        actualizarTablaTiquetes(sorteo.getGestorTiquetes().getListaTiquete());
    }//GEN-LAST:event_botonEliminarTiqueteActionPerformed

    private void pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosActionPerformed
        VistaPrincipal vista = new VistaPrincipal(this.tablaTiquetes.getModel());
        vista.setVisible(true);
    }//GEN-LAST:event_pedidosActionPerformed
   
    
    public void actualizarTablaTiquetes(DoubleLinkedList<Tiquete> listaTiquetes){
        ModeladorTablas.vaciarTabla(tablaTiquetes);
        Object[] filaNueva;
        DoubleLinkedNode<Tiquete> temp = listaTiquetes.getHead();
        for (int i = 0; i < listaTiquetes.getSize(); i++) {
            filaNueva = new Object[]{temp.getElement().getEmisor(),
                temp.getElement().getTipoSorteo(),
                temp.getElement().getPrecio(),
                temp.getElement().getNumero(),
                temp.getElement().getSorteo().getCodigo(),
            temp.getElement().getUsuario()};
            ModeladorTablas.nuevaFila(tablaTiquetes, filaNueva);
            temp = temp.getNext();
        }
    }
    
    public void actualizarTablaTipo(DoubleLinkedList<Sorteo> tablaSorteo){
        ModeladorTablas.vaciarTabla(tablaSorteos);
        Object[] filaNueva;
        DoubleLinkedNode<Sorteo> temp = tablaSorteo.getHead();
        for (int i = 0; i < tablaSorteo.getSize(); i++) {
            filaNueva = new Object[]{temp.getElement().getCodigo(),
                temp.getElement().getNombreSorteo(),
                temp.getElement().getEmisiones(),
                temp.getElement().getFecha(),
                temp.getElement().getTipo()};
            ModeladorTablas.nuevaFila(tablaSorteos, filaNueva);
            temp = temp.getNext();
        }
    }
    
    public void actualizarTabla() {

        ModeladorTablas.vaciarTabla(tablaSorteos);
        Object[] filaNueva;
        DoubleLinkedNode<Sorteo> temp = gestionSorteo.getListaSorteo().getHead();
        for (int i = 0; i < gestionSorteo.getListaSorteo().getSize(); i++) {
            filaNueva = new Object[]{temp.getElement().getCodigo(),
                temp.getElement().getNombreSorteo(),
                temp.getElement().getEmisiones(),
                temp.getElement().getFecha(),
                temp.getElement().getTipo()};
            ModeladorTablas.nuevaFila(tablaSorteos, filaNueva);
            temp = temp.getNext();
        }
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sorteos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonBusquedaFecha;
    private javax.swing.JButton botonBusquedaNombre;
    private javax.swing.JButton botonBusquedaNumero;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonEliminarTiquete;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonIngresarSorteo;
    private javax.swing.JButton botonTipo;
    private javax.swing.JButton botonTiqueteSorteos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelEmisiones;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JButton pedidos;
    private javax.swing.JTable tablaSorteos;
    private javax.swing.JTable tablaTiquetes;
    private javax.swing.JTextField txtBuscarFecha;
    private javax.swing.JTextField txtBusquedaNombre;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoBusquedaNumero;
    private javax.swing.JTextField txtCodigoSorteo;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtEmisiones;
    private javax.swing.JTextField txtEmisor;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioFinal;
    private javax.swing.JTextField txtPrecioInicial;
    private javax.swing.JComboBox<String> txtTipo;
    private javax.swing.JTextField txtTipoSorteo;
    private javax.swing.JTextField txtTiquetesSorteo;
    private javax.swing.JComboBox<String> txttipo2;
    // End of variables declaration//GEN-END:variables
}
