/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotoTEC.vista;

import javax.swing.JTable;
import javax.swing.table.TableModel;
import lotoTEC.logica.GestionPedido;
import lotoTEC.logica.Sorteo;
import lotoTEC.logica.Tiquete;
import lotoTEC.logica.Usuario;

/**
 *
 * @author Mata
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    Usuario usuario;
    Sorteos pantallaSorteos;
    GestionPedido gestionPedido;
    public VistaPrincipal(TableModel tablaTiquetes) {
        this.gestionPedido = new GestionPedido(pantallaSorteos.getGestionSorteo());
        initComponents();
        this.tablaTiquetesPedidos.setModel(tablaTiquetes);
    }
        public VistaPrincipal() {        
        initComponents();
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Sorteos getPantallaSorteos() {
        return pantallaSorteos;
    }

    public void setPantallaSorteos(Sorteos pantallaSorteos) {
        this.pantallaSorteos = pantallaSorteos;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNombre = new javax.swing.JTextField();
        nombreEtiqueta = new javax.swing.JLabel();
        cedulaEtiqueta = new javax.swing.JLabel();
        campoCedula = new javax.swing.JTextField();
        etiquetaTelefono = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        etiquetaEdad = new javax.swing.JLabel();
        campoEdad = new javax.swing.JTextField();
        etiquetaDireccion = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        etiquetaCorreo = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        botonEliminarPedido = new javax.swing.JButton();
        botonCargarPedido = new javax.swing.JButton();
        botonRealizarPedido = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTiquetesPedidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoNombre.setToolTipText("");
        getContentPane().add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, 20));

        nombreEtiqueta.setText("Ingrese su nombre:");
        getContentPane().add(nombreEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 20));

        cedulaEtiqueta.setText("Cedula: ");
        getContentPane().add(cedulaEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        getContentPane().add(campoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 120, -1));

        etiquetaTelefono.setText("Telefono: ");
        getContentPane().add(etiquetaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        getContentPane().add(campoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, -1));

        etiquetaEdad.setText("Edad: ");
        getContentPane().add(etiquetaEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        getContentPane().add(campoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 120, -1));

        etiquetaDireccion.setText("Direccion: ");
        getContentPane().add(etiquetaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        getContentPane().add(campoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 120, 20));

        etiquetaCorreo.setText("Correo: ");
        getContentPane().add(etiquetaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        getContentPane().add(campoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 120, 20));

        botonIngresar.setText("Ingresar");
        botonIngresar.setActionCommand("ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 470, 170));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 260, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        botonEliminarPedido.setText("Eliminar");
        getContentPane().add(botonEliminarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 110, -1));

        botonCargarPedido.setText("Cargar Pedido");
        botonCargarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(botonCargarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 110, -1));

        botonRealizarPedido.setText("Realizar Pedido");
        getContentPane().add(botonRealizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 110, -1));

        tablaTiquetesPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Emisor", "Tipo Sorteo", "Precio", "Numero", "Codigo Sorteo", "Usuario"
            }
        ));
        jScrollPane3.setViewportView(tablaTiquetesPedidos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 460, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        String nombre = this.campoNombre.getText();
        String direccion = this.campoDireccion.getText();
        String correo = this.campoCorreo.getText();
        int cedula = Integer.parseInt(this.campoCedula.getText());
        int telefono = Integer.parseInt(this.campoTelefono.getText());
        int edad = Integer.parseInt(this.campoEdad.getText());
        Usuario usuario = new Usuario(nombre, edad, direccion, correo, cedula, telefono);
        setUsuario(usuario);
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonCargarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarPedidoActionPerformed
       int row = tablaTiquetesPedidos.getSelectedRow();
       String emisor = tablaTiquetesPedidos.getModel().getValueAt(row, 0).toString();
       String tipoSorteo = tablaTiquetesPedidos.getModel().getValueAt(row, 1).toString();
       int precio = Integer.parseInt(tablaTiquetesPedidos.getModel().getValueAt(row, 2).toString());
       int numero = Integer.parseInt(tablaTiquetesPedidos.getModel().getValueAt(row, 3).toString());
       int codigoSorteo = Integer.parseInt(tablaTiquetesPedidos.getModel().getValueAt(row, 4).toString());
       Sorteo sorteo = this.pantallaSorteos.getGestionSorteo().consultarPorCodigo(codigoSorteo);
       Tiquete tiquete = new Tiquete(emisor, tipoSorteo, precio, numero, sorteo);
       this.gestionPedido.cargarPedido(this.usuario, tiquete);
       actualizarTablaPedidoUsuario();
    }//GEN-LAST:event_botonCargarPedidoActionPerformed
    
    public void actualizarTablaPedidoUsuario(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarPedido;
    private javax.swing.JButton botonEliminarPedido;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonRealizarPedido;
    private javax.swing.JTextField campoCedula;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel cedulaEtiqueta;
    private javax.swing.JLabel etiquetaCorreo;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaEdad;
    private javax.swing.JLabel etiquetaTelefono;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nombreEtiqueta;
    private javax.swing.JTable tablaTiquetesPedidos;
    // End of variables declaration//GEN-END:variables
}
