/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotoTEC.vista;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import lotoTEC.estructuras.DoubleLinkedNode;
import lotoTEC.logica.GestionPedido;
import lotoTEC.logica.GestionSorteo;
import lotoTEC.logica.ModeladorTablas;
import lotoTEC.logica.Sorteo;
import lotoTEC.logica.Tiquete;
import lotoTEC.logica.Usuario;

/**
 *
 * @author Mata
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    Usuario usuario;
    GestionPedido gestionPedido;
    GestionSorteo gestorSorteos;
    public VistaPrincipal(TableModel tablaTiquetes, GestionSorteo gestorSorteo) {
        this.gestorSorteos = gestorSorteo;
        this.gestionPedido = new GestionPedido(gestorSorteo);
        initComponents();
        this.tablaTiquetesPedidos.setModel(tablaTiquetes);
    }
        public VistaPrincipal() {        
        initComponents();
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNombre = new javax.swing.JTextField();
        nombreEtiqueta = new javax.swing.JLabel();
        cedulaEtiqueta = new javax.swing.JLabel();
        campoCedula = new javax.swing.JTextField();
        etiquetaTelefono = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        etiquetaEdad = new javax.swing.JLabel();
        campoEdad = new javax.swing.JTextField();
        etiquetaDireccion = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        etiquetaCorreo = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        botonEliminarPedido = new javax.swing.JButton();
        botonCargarPedido = new javax.swing.JButton();
        botonRealizarPedido = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTiquetesAPedir = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaTiquetesPedidos = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaTiquetesPedidos2 = new javax.swing.JTable();
        botonPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoNombre.setToolTipText("");
        getContentPane().add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 120, 30));

        nombreEtiqueta.setText("Ingrese su nombre:");
        getContentPane().add(nombreEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 20));

        cedulaEtiqueta.setText("Cedula: ");
        getContentPane().add(cedulaEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        getContentPane().add(campoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, 30));

        etiquetaTelefono.setText("Telefono: ");
        getContentPane().add(etiquetaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        getContentPane().add(campoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 120, 30));

        etiquetaEdad.setText("Edad: ");
        getContentPane().add(etiquetaEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));
        getContentPane().add(campoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 120, 30));

        etiquetaDireccion.setText("Direccion: ");
        getContentPane().add(etiquetaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        getContentPane().add(campoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 30));

        etiquetaCorreo.setText("Correo: ");
        getContentPane().add(etiquetaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        getContentPane().add(campoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 120, 30));

        botonIngresar.setText("Ingresar");
        botonIngresar.setActionCommand("ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 260, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        botonEliminarPedido.setText("Eliminar");
        botonEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 110, -1));

        botonCargarPedido.setText("Cargar Pedido");
        botonCargarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(botonCargarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 110, -1));

        botonRealizarPedido.setText("Realizar Pedido");
        botonRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(botonRealizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 110, -1));

        tablaTiquetesAPedir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Emisor", "Tipo Sorteo", "Precio", "Numero", "Codigo Sorteo", "Usuario"
            }
        ));
        jScrollPane3.setViewportView(tablaTiquetesAPedir);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 460, 270));

        tablaTiquetesPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Emisor", "Tipo Sorteo", "Precio", "Numero", "Codigo Sorteo", "Usuario"
            }
        ));
        jScrollPane4.setViewportView(tablaTiquetesPedidos);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 460, 270));

        tablaTiquetesPedidos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Emisor", "Tipo Sorteo", "Precio", "Numero", "Codigo Sorteo", "Usuario"
            }
        ));
        jScrollPane5.setViewportView(tablaTiquetesPedidos2);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 460, 270));

        botonPedidos.setText("Pedidos");
        botonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(botonPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        String nombre = this.campoNombre.getText();
        String direccion = this.campoDireccion.getText();
        String correo = this.campoCorreo.getText();
        int cedula = Integer.parseInt(this.campoCedula.getText());
        int telefono = Integer.parseInt(this.campoTelefono.getText());
        int edad = Integer.parseInt(this.campoEdad.getText());
        Usuario usuario = new Usuario(nombre, edad, direccion, correo, cedula, telefono);
        setUsuario(usuario);
        JOptionPane.showMessageDialog(null, "Ingreso Usuario");
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonCargarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarPedidoActionPerformed
       int row = tablaTiquetesPedidos.getSelectedRow();
       String emisor = tablaTiquetesPedidos.getModel().getValueAt(row, 0).toString();
       String tipoSorteo = tablaTiquetesPedidos.getModel().getValueAt(row, 1).toString();
       int precio = Integer.parseInt(tablaTiquetesPedidos.getModel().getValueAt(row, 2).toString());
       int numero = Integer.parseInt(tablaTiquetesPedidos.getModel().getValueAt(row, 3).toString());
       int codigoSorteo = Integer.parseInt(tablaTiquetesPedidos.getModel().getValueAt(row, 4).toString());
       Sorteo sorteo = this.gestorSorteos.consultarPorCodigo(codigoSorteo);
       Tiquete tiquete = new Tiquete(emisor, tipoSorteo, precio, numero, sorteo);
       this.gestionPedido.cargarPedido(this.usuario, tiquete);
       
       actualizarTablaPedidoUsuario();
    }//GEN-LAST:event_botonCargarPedidoActionPerformed

    private void botonRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarPedidoActionPerformed
        this.gestionPedido.realizarPedido(this.usuario);
        JOptionPane.showMessageDialog(null, "Se ha realizado el pedido");
    }//GEN-LAST:event_botonRealizarPedidoActionPerformed

    private void botonEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPedidoActionPerformed
       int row = tablaTiquetesAPedir.getSelectedRow();
       String emisor = tablaTiquetesAPedir.getModel().getValueAt(row, 0).toString();
       String tipoSorteo = tablaTiquetesAPedir.getModel().getValueAt(row, 1).toString();
       int precio = Integer.parseInt(tablaTiquetesAPedir.getModel().getValueAt(row, 2).toString());
       int numero = Integer.parseInt(tablaTiquetesAPedir.getModel().getValueAt(row, 3).toString());
       int codigoSorteo = Integer.parseInt(tablaTiquetesAPedir.getModel().getValueAt(row, 4).toString());
       Sorteo sorteo = this.gestorSorteos.consultarPorCodigo(codigoSorteo);
       Tiquete tiquete = new Tiquete(emisor, tipoSorteo, precio, numero, sorteo);
       this.usuario.getTiquetesComprados().delete(tiquete);
       actualizarTablaPedidoUsuario();
    }//GEN-LAST:event_botonEliminarPedidoActionPerformed

    private void botonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedidosActionPerformed
       Pedidos vista = new Pedidos(this.gestionPedido);
        vista.setVisible(true);
    }//GEN-LAST:event_botonPedidosActionPerformed
    
    public void actualizarTablaPedidoUsuario(){
        ModeladorTablas.vaciarTabla(tablaTiquetesAPedir);
        Object[] filaNueva;
        DoubleLinkedNode<Tiquete> temp = this.usuario.getTiquetesComprados().getHead();
        for (int i = 0; i < this.usuario.getTiquetesComprados().getSize(); i++) {
            filaNueva = new Object[]{temp.getElement().getEmisor(),
                temp.getElement().getTipoSorteo(),
                temp.getElement().getPrecio(),
                temp.getElement().getNumero(),
                temp.getElement().getSorteo().getCodigo(),
            temp.getElement().getUsuario()};
            ModeladorTablas.nuevaFila(tablaTiquetesAPedir, filaNueva);
            temp = temp.getNext();
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarPedido;
    private javax.swing.JButton botonEliminarPedido;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonPedidos;
    private javax.swing.JButton botonRealizarPedido;
    private javax.swing.JTextField campoCedula;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel cedulaEtiqueta;
    private javax.swing.JLabel etiquetaCorreo;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaEdad;
    private javax.swing.JLabel etiquetaTelefono;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nombreEtiqueta;
    private javax.swing.JTable tablaTiquetesAPedir;
    private javax.swing.JTable tablaTiquetesPedidos;
    private javax.swing.JTable tablaTiquetesPedidos2;
    // End of variables declaration//GEN-END:variables
}
